# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/yunluo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),yunluo)

$(call add-radio-file-sha1-checked,radio/dpm.img,d040452bc4c9870745503d5bcace7f39b74b3f80)
$(call add-radio-file-sha1-checked,radio/gz.img,abdd0224d3bc02556f8ff8b9cd9a5f598a7d5491)
$(call add-radio-file-sha1-checked,radio/lk.img,efb704e19a3f1c8e032f8f0a5c8ae281733134f9)
$(call add-radio-file-sha1-checked,radio/logo.img,c0994a03206b2c6a381a97262eea8ac681aee320)
$(call add-radio-file-sha1-checked,radio/mcupm.img,463e74f726c7449bf17d4495b68a880da6eaf46f)
$(call add-radio-file-sha1-checked,radio/pi_img.img,1e3d00b31b66acb21c50d6206320457407478103)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,619b6eb6acb407d17e056a470b7777e94089715c)
$(call add-radio-file-sha1-checked,radio/scp.img,5df6d9dc30a6da723a638532d8aae4d900bd0fb8)
$(call add-radio-file-sha1-checked,radio/spmfw.img,6a9e246157f9098968794a9e3a007b1217c2f8d7)
$(call add-radio-file-sha1-checked,radio/sspm.img,14a6fd77d96dbace9f5996a3d81f5dbf46eba9c8)
$(call add-radio-file-sha1-checked,radio/tee.img,e27ac1b5f38f5da80a48d4afae4c7aa4a3e09e9d)

endif
