# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/yunluo/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    dpm \
    gz \
    lk \
    logo \
    mcupm \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee
